# This line needs to be before any sections:
palette = "gruvbox_dark"

format = """
$status\
[](orange)\
$directory\
$direenv\
[](fg:orange bg:yellow)\
$git_branch\
$git_status\
$git_state\
$git_metrics\
[](fg:yellow bg:green)\
$c\
$cmake\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:aqua)\
$custom\
[ ](fg:aqua)\
$cmd_duration\
$line_break\
[](red_dim)\
$os\
$username\
$hostname\
$memory_usage\
$battery\
$container\
$jobs\
$time\
[ ](red_dim)\
$shlvl\
$character"""

# https://github.com/morhetz/gruvbox (dark)
[palettes.gruvbox_dark]
bg0_h = "#1d2021"
bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
gray = "#928374"
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"
red = "#fb4934"
red_dim = "#cc241d"
red_faded = "#9d0006"
green = "#b8bb26"
green_dim = "#98971a"
yellow = "#fabd2f"
yellow_dim = "#d79921"
blue = "#83a598"
blue_dim = "#458588"
purple = "#d3869b"
purple_dim = "#b16286"
aqua = "#8ec07c"
aqua_dim = "#689d6a"
orange = "#fe8019"
orange_dim = "#d65d0e"

[os]
disabled = false
format = '[$symbol$version]($style)'
style = "bg:red_dim fg:bg0_h"

[os.symbols]
AlmaLinux = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = "󰣨"
Linux = ""
Macos = ""
Manjaro = ""
Mint = "󰣭"
NixOS = ""
openSUSE = ""
Pop = ""
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
RockyLinux = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = "󰖳"

#[shell]
#disabled = false

[hostname]
#disabled = false
ssh_only = true
#trim_at = ".sonic.net"
style = "bg:red_dim fg:bg0_h"
#style = "bold green"
format = "[@$hostname ]($style)"
#ssh_symbol = " "
ssh_symbol = ""

[username]
#show_always = true
disabled = false
style_user = "bg:red_dim fg:bg0_h"
style_root = "bg:red_dim fg:bg0_h"
format = '[ $user]($style)'

[directory]
style = "bg:orange fg:bg0_h"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " "
"Code" = "󰲋 "
"~/Code" = "󰲋 "
"Developer" = "󰲋 "
"~/Developer" = "󰲋 "
"Documents" = "󰈙 "
"~/Documents" = "󰈙 "
"Downloads" = " "
"~/Downloads" = " "
"GoogleDrive" = " "
"Music" = "󰝚 "
"~/Music" = "󰝚 "
"Pictures" = " "
"~/Pictures" = " "
"repos" = "󰲋 "
"Repos" = "󰲋 "
"~/repos" = "󰲋 "
"~/Repos" = "󰲋 "


[time]
#disabled = false
use_12hr = true
time_range = '16:00:00-09:30:00'
style = "bg:red_dim"
format = '[[ $time ](fg:bg0_h bg:red_dim)]($style)'
time_format="%-I:%M%P"

[[battery.display]]
threshold = 75
style = "bg:aqua fg:bg0_h"

[memory_usage]
#symbol = " "
disabled = false
style = "bg:red_dim fg:bg0_h"
format = "[ $symbol${ram}(|${swap}) ]($style)"
#symbol = ""
#symbol = "󰍛"
symbol = ""

[shlvl]
disabled = false
#style = "bg:red_dim fg:bg0_h"
format = "[$symbol$shlvl]($style)"
symbol = "↕"

[status]
disabled = false
style = "bg:red fg:bg0_h"
format = "[](fg:red)[ $symbol$status ]($style)[ ](fg:red)"

[git_branch]
format = '[[ $symbol$branch ](fg:bg0_h bg:yellow)]($style)'
symbol = ""
truncation_length = 16
style = "bg:yellow"


[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:bg0_h bg:yellow)]($style)'

[git_metrics]
#disabled = false
added_style = "bg:yellow fg:green_dim"
deleted_style = "bg:yellow fg:red_faded"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[c]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[java]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version) ](fg:bg0_h bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol($version)(\(#$virtualenv\)) ](fg:bg0_h bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:aqua"
format = '[[ $symbol($context) ](fg:bg0_h bg:aqua)]($style)'

[container]
style = "fg:red_dim bg:aqua"
format = '[[$symbol($context) ](fg:bg0_h bg:aqua)]($style)[](fg:aqua bg:red_dim)'

[conda]
symbol = ""
style = "fg:bg0_h bg:aqua"
format = '[$symbol$environment ]($style)'
ignore_base = false

[custom.ssh_no_keys]
description = "SSH missing keys"
when = "ssh-add -l | grep -q 'no identities'"
command = "echo "
format = "[ $symbol$output]($style)"
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:bg0_h bg:aqua"

[custom.ssh_keys]
description = "SSH key count"
when = "ssh-add -l | grep -v -q 'no identities'"
command = "ssh-add -l | grep -v 'no identities' | wc -l"
format = "[ $symbol$output]($style)"
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:bg0_h bg:aqua"

[custom.tailscale_status]
description = "Tailscale Status"
command="tailscale-status.sh"
when="command -v tailscale-status.sh"
format = "[ $symbol$output]($style)"
shell = ["bash", "--noprofile", "--norc"]
symbol = "󱗼"
style = "fg:bg0_h bg:aqua"

[custom.screen]
description = "Display a monitor glyph and the pid.tty.host if we're in a screen session."
when = """ test "$STY" """
shell = ["bash", "--noprofile", "--norc"]
#command = 'echo 🖵 " $STY"'
command = 'echo " $STY"'
style = "fg:bg0_h bg:aqua"

[custom.systemctl]
description = "Count failed systemd units"
when = "systemctl --failed | grep failed"
command = "systemctl --failed | grep 'loaded units listed' | cut -d' ' -f1"
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:bg0_h bg:aqua"

[custom.loadavg]
description = "show load averages"
command = "cut -d' ' -f 1,2,3 /proc/loadavg"
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:bg0_h bg:aqua"
when = """
limit="1.0"
load=$(cut -d' ' -f 1 /proc/loadavg)
test "$(echo "$load>$limit" | bc)" -ne 0
"""
